ip: 0.0.0.0
port: 8181
token_files:
  client: ./client_tokens.txt
  server: ./server_tokens.txt
  admin: ./admin_tokens.txt
rate_limit:
  interval: 10000
  max_burst: 6
guard:
  kick_count: 10
  ban_time: 24
  record_file: ./guard_record
log:
  enable_file: true
  file_directory: ./logs
  level: INFO
